### ISSUE TITLE
NameError: name 'x' is not defined in function aggregate_stats

### ISSUE THREAD

**Issue by yuzhujiutian** [Muntadher91/Pandas#1]
I found your sharing when I was learning pandas. Thank you very much.

<br/>
code on colab:

https://colab.research.google.com/drive/1XpLyHKxZl45SndoXEULI1hhbytgccbo-?usp=sharing

the code, same as your file [Serie A.py](https://github.com/Muntadher91/Pandas/tree/master/Serie%20A)

run it on google colab, and get the errors as follows

<br/>
error:

![image](https://user-images.githubusercontent.com/386347/83428158-7bdd3180-a464-11ea-841f-65cb2018a13e.png)

**Comment by Muntadher91** [comment]
Hello,

Thanks for the notification, that was a typo. I fixed it now, you can check the updated .py file in the repo.

**Comment by yuzhujiutian** [comment]
Tt's OK now. Thank you

![image](https://user-images.githubusercontent.com/386347/83464550-c16d1f00-a4a3-11ea-9b29-a05ed5940bab.png)
